/**
 * Script para cargar especies arbóreas típicas de México en el catálogo
 */
import { db } from "./db";
import { treeSpecies } from "@shared/schema";

export async function seedTreeSpecies() {
  try {
    console.log("Cargando especies arbóreas de México...");
    
    // Verificar si ya existen especies en la base de datos
    const existingSpecies = await db.select({ count: treeSpecies.id }).from(treeSpecies);
    
    if (existingSpecies[0]?.count > 0) {
      console.log(`Ya existen ${existingSpecies[0].count} especies en la base de datos.`);
      return { success: true, message: "Las especies ya estaban cargadas" };
    }
    
    // Lista de especies arbóreas típicas de México
    const mexicanTreeSpecies = [
      {
        commonName: "Ahuehuete (Sabino)",
        scientificName: "Taxodium mucronatum",
        family: "Cupressaceae",
        origin: "Nativo",
        climateZone: "Templado húmedo",
        growthRate: "Medio",
        heightMature: 30,
        canopyDiameter: 15,
        lifespan: 1500,
        description: "Árbol nacional de México, de gran longevidad y relacionado con cuerpos de agua. Sus raíces son importantes para estabilizar las riberas de ríos.",
        maintenanceRequirements: "Requiere abundante agua y suelos bien drenados. Poda de formación en etapas juveniles.",
        waterRequirements: "Alto",
        sunRequirements: "Pleno sol",
        soilRequirements: "Profundo y húmedo",
        ecologicalBenefits: "Hábitat para aves, control de erosión, estabilización de riberas, purificación de agua",
        ornamentalValue: "Alto",
        commonUses: "Ornamental, reforestación, estabilización de riberas",
        isEndangered: false,
        iconColor: "#2E7D32"
      },
      {
        commonName: "Encino",
        scientificName: "Quercus spp.",
        family: "Fagaceae",
        origin: "Nativo",
        climateZone: "Templado",
        growthRate: "Lento",
        heightMature: 25,
        canopyDiameter: 20,
        lifespan: 300,
        description: "México es el país con mayor diversidad de encinos en el mundo. Son árboles fundamentales en los ecosistemas templados del país.",
        maintenanceRequirements: "Poda ligera para eliminar ramas muertas o enfermas. Resistente a la sequía una vez establecido.",
        waterRequirements: "Medio",
        sunRequirements: "Pleno sol a sombra parcial",
        soilRequirements: "Bien drenado, tolera suelos pobres",
        ecologicalBenefits: "Hábitat y alimento para fauna, control de erosión, captura de carbono",
        ornamentalValue: "Alto",
        commonUses: "Reforestación, ornamental, madera, combustible",
        isEndangered: false,
        iconColor: "#33691E"
      },
      {
        commonName: "Ceiba (Pochote)",
        scientificName: "Ceiba pentandra",
        family: "Malvaceae",
        origin: "Nativo",
        climateZone: "Tropical",
        growthRate: "Rápido",
        heightMature: 35,
        canopyDiameter: 30,
        lifespan: 200,
        description: "Considerado árbol sagrado por los mayas (Árbol de la Vida). Reconocible por su tronco con espinas y el ensanchamiento en la base.",
        maintenanceRequirements: "Sensible a las heladas. Requiere poda cuidadosa para formar su estructura.",
        waterRequirements: "Medio",
        sunRequirements: "Pleno sol",
        soilRequirements: "Suelos profundos y bien drenados",
        ecologicalBenefits: "Hábitat para vida silvestre, fijación de nitrógeno, sombreado",
        ornamentalValue: "Alto",
        commonUses: "Ornamental, cultural, fibras, medicinal",
        isEndangered: false,
        iconColor: "#795548"
      },
      {
        commonName: "Palo Blanco",
        scientificName: "Lysiloma divaricatum",
        family: "Fabaceae",
        origin: "Nativo",
        climateZone: "Semiárido",
        growthRate: "Medio",
        heightMature: 12,
        canopyDiameter: 10,
        lifespan: 80,
        description: "Árbol resistente a la sequía, con tronco blanco distintivo. Importante en ecosistemas semiáridos de México.",
        maintenanceRequirements: "Resistente a sequía, poda mínima requerida.",
        waterRequirements: "Bajo",
        sunRequirements: "Pleno sol",
        soilRequirements: "Tolera suelos pobres y pedregosos",
        ecologicalBenefits: "Fijación de nitrógeno, control de erosión, refugio para fauna",
        ornamentalValue: "Medio",
        commonUses: "Restauración ecológica, ornamental, sombra",
        isEndangered: false,
        iconColor: "#BDBDBD"
      },
      {
        commonName: "Huizache",
        scientificName: "Acacia farnesiana",
        family: "Fabaceae",
        origin: "Nativo",
        climateZone: "Árido y semiárido",
        growthRate: "Rápido",
        heightMature: 9,
        canopyDiameter: 8,
        lifespan: 60,
        description: "Árbol espinoso adaptado a zonas áridas. Sus flores amarillas son aromáticas y atractivas para polinizadores.",
        maintenanceRequirements: "Muy resistente a sequía, poda de formación recomendada.",
        waterRequirements: "Bajo",
        sunRequirements: "Pleno sol",
        soilRequirements: "Adaptable, tolera suelos pobres",
        ecologicalBenefits: "Fijación de nitrógeno, control de erosión, hábitat para fauna",
        ornamentalValue: "Medio",
        commonUses: "Restauración de suelos, cercos vivos, melífero, forraje",
        isEndangered: false,
        iconColor: "#FFC107"
      },
      {
        commonName: "Parota",
        scientificName: "Enterolobium cyclocarpum",
        family: "Fabaceae",
        origin: "Nativo",
        climateZone: "Tropical y subtropical",
        growthRate: "Rápido",
        heightMature: 30,
        canopyDiameter: 35,
        lifespan: 150,
        description: "Árbol imponente de la selva tropical con copa amplia que proporciona excelente sombra. Sus frutos son distintivos en forma de oreja.",
        maintenanceRequirements: "Poda para formar estructura y eliminar ramas muertas.",
        waterRequirements: "Medio",
        sunRequirements: "Pleno sol",
        soilRequirements: "Bien drenados, tolera suelos alcalinos",
        ecologicalBenefits: "Fijación de nitrógeno, hábitat para fauna, sombra",
        ornamentalValue: "Alto",
        commonUses: "Ornamental, sombra, madera, restauración ecológica",
        isEndangered: false,
        iconColor: "#558B2F"
      },
      {
        commonName: "Fresno",
        scientificName: "Fraxinus uhdei",
        family: "Oleaceae",
        origin: "Nativo",
        climateZone: "Templado",
        growthRate: "Rápido",
        heightMature: 25,
        canopyDiameter: 15,
        lifespan: 80,
        description: "Árbol caducifolio de rápido crecimiento, muy utilizado en la forestación urbana en el centro de México.",
        maintenanceRequirements: "Requiere poda regular para formar estructura adecuada.",
        waterRequirements: "Medio",
        sunRequirements: "Pleno sol",
        soilRequirements: "Prefiere suelos profundos y húmedos",
        ecologicalBenefits: "Captura de carbono, hábitat para aves, sombra urbana",
        ornamentalValue: "Medio",
        commonUses: "Forestación urbana, ornamental, madera",
        isEndangered: false,
        iconColor: "#8BC34A"
      },
      {
        commonName: "Jacaranda",
        scientificName: "Jacaranda mimosifolia",
        family: "Bignoniaceae",
        origin: "Introducido (Sudamérica)",
        climateZone: "Subtropical",
        growthRate: "Medio",
        heightMature: 15,
        canopyDiameter: 12,
        lifespan: 70,
        description: "Árbol ornamental muy apreciado por sus espectaculares flores azul-violeta que tiñen las ciudades en primavera.",
        maintenanceRequirements: "Poda anual para mantener forma y eliminar ramas secas.",
        waterRequirements: "Medio",
        sunRequirements: "Pleno sol",
        soilRequirements: "Bien drenados, no tolera encharcamiento",
        ecologicalBenefits: "Atrae polinizadores, sombra urbana",
        ornamentalValue: "Alto",
        commonUses: "Ornamental urbano, forestación de avenidas",
        isEndangered: false,
        iconColor: "#9575CD"
      },
      {
        commonName: "Primavera",
        scientificName: "Tabebuia rosea",
        family: "Bignoniaceae",
        origin: "Nativo",
        climateZone: "Tropical y subtropical",
        growthRate: "Medio",
        heightMature: 25,
        canopyDiameter: 15,
        lifespan: 100,
        description: "Conocido por sus espectaculares floraciones rosadas en temporada seca cuando el árbol está sin hojas.",
        maintenanceRequirements: "Poda para formar estructura y eliminar ramas secas.",
        waterRequirements: "Medio",
        sunRequirements: "Pleno sol",
        soilRequirements: "Bien drenados, tolera suelos pobres",
        ecologicalBenefits: "Atrae polinizadores, hábitat para fauna, sombra",
        ornamentalValue: "Alto",
        commonUses: "Ornamental, forestación urbana, madera",
        isEndangered: false,
        iconColor: "#F48FB1"
      },
      {
        commonName: "Guamúchil",
        scientificName: "Pithecellobium dulce",
        family: "Fabaceae",
        origin: "Nativo",
        climateZone: "Tropical y subtropical",
        growthRate: "Medio",
        heightMature: 15,
        canopyDiameter: 15,
        lifespan: 80,
        description: "Árbol espinoso con frutos comestibles y vainas retorcidas. Muy adaptable a diferentes condiciones.",
        maintenanceRequirements: "Resistente a sequía, poda mínima requerida.",
        waterRequirements: "Bajo",
        sunRequirements: "Pleno sol",
        soilRequirements: "Adaptable, tolera salinidad",
        ecologicalBenefits: "Fijación de nitrógeno, control de erosión, alimento para fauna",
        ornamentalValue: "Medio",
        commonUses: "Frutos comestibles, restauración ecológica, cercos vivos",
        isEndangered: false,
        iconColor: "#8D6E63"
      },
      {
        commonName: "Cedro Rojo",
        scientificName: "Cedrela odorata",
        family: "Meliaceae",
        origin: "Nativo",
        climateZone: "Tropical",
        growthRate: "Rápido",
        heightMature: 35,
        canopyDiameter: 20,
        lifespan: 200,
        description: "Árbol maderable de gran importancia económica y ecológica. Su madera es aromática y resistente a plagas.",
        maintenanceRequirements: "Vulnerable a la barrenador del tallo en etapas juveniles.",
        waterRequirements: "Medio",
        sunRequirements: "Pleno sol a sombra parcial",
        soilRequirements: "Bien drenados, profundos",
        ecologicalBenefits: "Hábitat para fauna, captura de carbono",
        ornamentalValue: "Alto",
        commonUses: "Maderable, ornamental, restauración ecológica",
        isEndangered: true,
        iconColor: "#BF360C"
      },
      {
        commonName: "Palmera Washingtonia",
        scientificName: "Washingtonia robusta",
        family: "Arecaceae",
        origin: "Nativo (norte de México)",
        climateZone: "Árido",
        growthRate: "Medio",
        heightMature: 25,
        canopyDiameter: 4,
        lifespan: 100,
        description: "Palmera alta y esbelta, muy utilizada en paisajismo urbano. Originaria del norte de México.",
        maintenanceRequirements: "Limpieza de hojas secas, requiere riego regular en temporada seca.",
        waterRequirements: "Medio",
        sunRequirements: "Pleno sol",
        soilRequirements: "Bien drenados, arenosos",
        ecologicalBenefits: "Hábitat para aves, resistente a sequía",
        ornamentalValue: "Alto",
        commonUses: "Ornamental, alineaciones urbanas",
        isEndangered: false,
        iconColor: "#4CAF50"
      },
      {
        commonName: "Lluvia de Oro",
        scientificName: "Cassia fistula",
        family: "Fabaceae",
        origin: "Introducido (Asia)",
        climateZone: "Tropical",
        growthRate: "Rápido",
        heightMature: 12,
        canopyDiameter: 10,
        lifespan: 60,
        description: "Árbol ornamental con espectaculares racimos colgantes de flores amarillas que aparecen en primavera y verano.",
        maintenanceRequirements: "Poda para formar estructura y controlar crecimiento.",
        waterRequirements: "Medio",
        sunRequirements: "Pleno sol",
        soilRequirements: "Bien drenados, tolera variedad de suelos",
        ecologicalBenefits: "Atrae polinizadores, sombra",
        ornamentalValue: "Alto",
        commonUses: "Ornamental, forestación urbana",
        isEndangered: false,
        iconColor: "#FFC107"
      },
      {
        commonName: "Oyamel",
        scientificName: "Abies religiosa",
        family: "Pinaceae",
        origin: "Nativo",
        climateZone: "Templado frío",
        growthRate: "Lento",
        heightMature: 40,
        canopyDiameter: 10,
        lifespan: 300,
        description: "Conífera de montaña, fundamental para el hábitat de la mariposa monarca. Endémico de las montañas del centro de México.",
        maintenanceRequirements: "Sensible a contaminación y sequía, requiere clima fresco.",
        waterRequirements: "Alto",
        sunRequirements: "Pleno sol a sombra parcial",
        soilRequirements: "Profundo, bien drenado, rico en materia orgánica",
        ecologicalBenefits: "Hábitat para mariposa monarca, captura de carbono, retención de agua",
        ornamentalValue: "Alto",
        commonUses: "Reservas ecológicas, reforestación, maderable",
        isEndangered: true,
        iconColor: "#004D40"
      },
      {
        commonName: "Colorín",
        scientificName: "Erythrina americana",
        family: "Fabaceae",
        origin: "Nativo",
        climateZone: "Subtropical",
        growthRate: "Rápido",
        heightMature: 10,
        canopyDiameter: 8,
        lifespan: 70,
        description: "Árbol con espectaculares flores rojas que aparecen cuando el árbol está sin hojas. Importante en la cultura mexicana.",
        maintenanceRequirements: "Poda regular para formación y control de crecimiento.",
        waterRequirements: "Bajo",
        sunRequirements: "Pleno sol",
        soilRequirements: "Adaptable, tolera suelos pobres",
        ecologicalBenefits: "Atrae colibríes, fijación de nitrógeno",
        ornamentalValue: "Alto",
        commonUses: "Ornamental, cercas vivas, alimenticio (flores comestibles)",
        isEndangered: false,
        iconColor: "#F44336"
      }
    ];
    
    // Insertar especies en la base de datos
    const result = await db.insert(treeSpecies).values(mexicanTreeSpecies).returning();
    
    console.log(`Se han cargado ${result.length} especies arbóreas en la base de datos.`);
    return { success: true, message: `${result.length} especies cargadas correctamente` };
  } catch (error) {
    console.error("Error al cargar las especies arbóreas:", error);
    return { success: false, message: "Error al cargar especies arbóreas", error };
  }
}

// Para ES modules no podemos usar require.main === module
// En lugar de eso, exportamos la función directamente